export default {
  default: '#222',
  primary: '#0D47A1',
  secondary: '#FF6F00',
  success: '#4CAF50',
  error: '#D50000',
  warning: '#FFCA28',
  info: '#EEEEEE',

  textDefault: '#fff',
  textPrimary: '#fff',
  textSecondary: '#fff',
  textSuccess: '#fff',
  textError: '#fff',
  textWarning: '#222',
  textInfo: '#222',

  backgroundDefault: '#222',
  backgroundPrimary: '#0D47A1',
  backgroundSecondary: '#FF6F00',
  backgroundSuccess: '#4CAF50',
  backgroundError: '#D50000',
  backgroundWarning: '#FFCA28',
  backgroundInfo: '#EEEEEE',

  // named colors
  alertBackgroundError: '#160b0b',
  alertTextError: '#f4c8c8',
  alertBackgroundSuccess: '#0b110c',
  alertTextSuccess: '#cce8cd',
  alertBackgroundWarning: '#191207',
  alertTextWarning: '#ffe2b7',
  alertBackgroundInfo: '#061216',
  alertTextInfo: '#b6e5f9',
};
