export default {
  default: '#f9f9f9',
  primary: '#0D47A1',
  secondary: '#FF6F00',
  success: '#4CAF50',
  error: '#D50000',
  warning: '#FFCA28',
  info: '#EEEEEE',

  textDefault: '#222',
  textPrimary: '#fff',
  textSecondary: '#fff',
  textSuccess: '#fff',
  textError: '#fff',
  textWarning: '#222',
  textInfo: '#222',

  backgroundDefault: '#f9f9f9',
  backgroundPrimary: '#0D47A1',
  backgroundSecondary: '#FF6F00',
  backgroundSuccess: '#4CAF50',
  backgroundError: '#D50000',
  backgroundWarning: '#FFCA28',
  backgroundInfo: '#EEEEEE',
};
